services:
  - type: web
    name: MYAROU-BLOG
    env: python
    plan: free

    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput

    startCommand: gunicorn blog_project.wsgi:application
